# Generated by Django 5.1 on 2024-09-11 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='bus_category',
        ),
        migrations.AddField(
            model_name='bus',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='seat_remaining',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fare', models.IntegerField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('seats', models.IntegerField()),
                ('ticket_taken', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='owner.bus')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
