# Generated by Django 5.1 on 2024-09-12 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_remove_bus_bus_category_bus_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
