# Generated by Django 5.1 on 2024-09-12 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_userticket'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTicket',
            new_name='Ticket',
        ),
    ]
