# Generated by Django 5.1 on 2024-09-13 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_rename_userticket_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
