# Generated by Django 5.1 on 2024-09-16 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0008_ticket_payment_method_ticket_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='payment_status',
        ),
    ]
