# Generated by Django 5.1 on 2024-09-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0011_ticketbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='total_fare',
            field=models.IntegerField(null=True),
        ),
    ]
