# Generated by Django 5.1 on 2024-09-20 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0012_tickets_total_fare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='total_fare',
        ),
    ]
