# Generated by Django 5.1 on 2024-09-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0013_remove_tickets_total_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='total_fare',
            field=models.IntegerField(null=True),
        ),
    ]
