# Generated by Django 5.1 on 2024-09-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0016_bus_cancellation_policy_bus_refund_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='arrival',
            field=models.DateTimeField(null=True),
        ),
    ]
