# Generated by Django 5.1 on 2024-09-22 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0018_bus_arrival_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='arrival_date',
        ),
    ]
